### ISSUE TITLE
ios - PrivacyDashboard SDK version specifying removed

### ISSUE THREAD

**Issue by lijogeorgep** [decentralised-dataexchange/data4diabetes-app#122]
Removed the 'PrivacyDashboardiOS' SDK version number to prevent the need for updating it every time there's a change in the SDK.  This modification ensures that the code will automatically execute the latest version of the SDK.

**Comment by lalc** [comment]
@lijogeorgep Could you please add this as a note in the developer document?

**Comment by lijogeorgep** [comment]
@lalc ok. I will add this in developer document
