### ISSUE TITLE
On localisation, scan and check expands in IOS

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/data4diabetes-app#19]
On localization, scan and check expands 

![Screenshot 2023-05-03 at 4 42 14 PM](https://user-images.githubusercontent.com/92527972/235951674-144403b4-036a-43b9-9dce-b208760c24f9.jpeg)

**Comment by josmilan** [comment]
@lijogeorgep please check this. try reducing the font size

@lalc is there a possibility or finding a new name for it, since even if we reduce the text size, there is a possibility of getting cut in smaller devices such as iPhone mini versions

**Comment by lalc** [comment]
Make it only Check?

**Comment by lijogeorgep** [comment]
@lalc So the change is 'check' instead of 'Scan & Check'. Isn't it?
