### ISSUE TITLE
Implement Food: Scan and Check tab screen

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/data4diabetes-app#3]
- [x] Page title should be Food: Scan and Check.
- [x] Camera part can be dummy in the first cut.
- [x] The following data is static - Carbohydrates: 80 Glycemic index: 94 Recommended insulin units: 8
- [x] Confirm and 'Reject and Change' buttons are dummy.
- [x] Scan and Check tab should be active.

**Comment by lijogeorgep** [comment]
Done

**Comment by georgepadayatti** [comment]
> Done

Awesome, from next commit onwards could you refer issue numbers in the commit message. "Fix #<issue number>". Once you do so, this issue will get notified a change was made against.
