### ISSUE TITLE
Crashlytics detected a missing dSYM

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/data4diabetes-app#81]

**Comment by lijogeorgep** [comment]
Locate the dSYM file: The dSYM file is generated when you build your app using Xcode. By default, it is stored in the app's derived data folder. You can find the dSYM file by navigating to the following path:

~/Library/Developer/Xcode/DerivedData/<YourAppName>/Build/Products/<YourAppTarget>/
Replace <YourAppName> with the name of your app and <YourAppTarget> with the target name for which you are missing the dSYM file.

Zip the dSYM file: Once you've located the dSYM file, right-click on it and select "Compress" or "Create Archive." This action will create a compressed zip file containing the dSYM file.

Upload the dSYM file to Firebase: Go to the Firebase console (https://console.firebase.google.com/), select your project, and navigate to the Crashlytics section. From there, click on the "Upload missing symbol files" button. Follow the on-screen instructions to upload the zipped dSYM file.

Wait for processing: After uploading the dSYM file, Firebase will process it and associate it with the corresponding app version. This process may take some time, especially if there are a large number of crash reports. You'll receive an email notification once the symbolication process is complete.

Verify the symbolication: Once the symbolication process is finished, Crashlytics will be able to fully symbolicate the crash reports for the affected version. You can check the Firebase console to ensure that the missing dSYM warning is no longer present.
